### ISSUE TITLE
[CMake] Do not use manual External Dependencies.

### ISSUE THREAD

**Issue by ghost** [sabarnac/game-tutorial#1]
Kitware provides a `FindGLEW` starting from CMake Ver `3.1`.

Use git Sub modules if exists.

Use `find_package` instead of manually writing the dependencies.

**Comment by ghost** [comment]
Closing this due to various reasons explained in private, namely that this repository is meant as a tutorial.

**Comment by sabarnac** [comment]
Closed in favour of #2
